---
apiVersion: v1
kind: Service
metadata:
  name: batch-processing-service
spec:
  selector:
    app: batch-processing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-processing-service
  labels:
    app: batch-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-processing-service
  template:
    metadata:
      labels:
        app: batch-processing-service
    spec:
      containers:
        - name: batch-processing-service
          image: skaminskiy/batch-processing-service:version1.0
          ports:
            - containerPort: 80
